CREATE TABLE `vehicle_maintenance` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`vehicle_id` integer NOT NULL,
	`station_id` integer NOT NULL,
	`request_date` text NOT NULL,
	`department` text NOT NULL,
	`odometer_km` real NOT NULL,
	`requested_repair` text NOT NULL,
	`failure_cause` text,
	`driver_name` text NOT NULL,
	`center_manager_name` text,
	`circle_manager_name` text,
	`attachment_key` text NOT NULL,
	`attachment_name` text NOT NULL,
	`attachment_type` text NOT NULL,
	`status` text DEFAULT 'open' NOT NULL,
	`maintenance_recommendation` text,
	`manager_recommendation` text,
	`finance_recommendation` text,
	`administrative_recommendation` text,
	`performed_work` text,
	`received_at` text,
	`received_by` text,
	`created_by` text NOT NULL,
	`closed_by` text,
	`created_at` text DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	`updated_at` text DEFAULT 'CURRENT_TIMESTAMP' NOT NULL,
	FOREIGN KEY (`vehicle_id`) REFERENCES `vehicles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`station_id`) REFERENCES `stations`(`id`) ON UPDATE no action ON DELETE no action
);
