"use client";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { HeartPulse,LockKeyhole,UserRound } from "lucide-react";

export default function AuthForm({setup=false}:{setup?:boolean}){const router=useRouter();const [form,setForm]=useState({fullName:"",username:"",password:"",confirm:""});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
useEffect(()=>{fetch("/api/auth/status").then(r=>r.json()).then(s=>{if(s.authenticated)router.replace("/");else if(s.needsSetup&&!setup)router.replace("/setup");else if(!s.needsSetup&&setup)router.replace("/login");});},[router,setup]);
async function submit(e:FormEvent){e.preventDefault();setError("");if(setup&&form.password!==form.confirm){setError("كلمتا المرور غير متطابقتين");return;}setBusy(true);const r=await fetch(setup?"/api/auth/setup":"/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"تعذر تسجيل الدخول");return;}window.location.href="/";}
return <main className="auth-page" dir="rtl"><section className="auth-brand"><div className="auth-logo"><HeartPulse/></div><h1>نظام الإحصائيات اليومية</h1><p>دائرة الإسعاف والطوارئ<br/>الهلال الأحمر الفلسطيني</p><span>نظام داخلي مؤمّن لإدارة العمليات اليومية</span></section><section className="auth-panel"><form onSubmit={submit}><small>{setup?"التهيئة الأولى":"تسجيل الدخول"}</small><h2>{setup?"إنشاء مدير النظام":"مرحبًا بعودتك"}</h2><p>{setup?"أنشئي أول حساب مدير. لن تظهر هذه الصفحة بعد إكمال الإعداد.":"أدخلي بيانات حسابك للوصول إلى النظام."}</p>{setup&&<label>الاسم الكامل<div><UserRound/><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></div></label>}<label>اسم المستخدم أو البريد<div><UserRound/><input required autoComplete="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></div></label><label>كلمة المرور<div><LockKeyhole/><input required minLength={8} type="password" autoComplete={setup?"new-password":"current-password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div></label>{setup&&<label>تأكيد كلمة المرور<div><LockKeyhole/><input required minLength={8} type="password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></div></label>}{error&&<div className="auth-error">{error}</div>}<button disabled={busy}>{busy?"جاري الحفظ...":setup?"إنشاء المدير والدخول":"دخول إلى النظام"}</button></form></section></main>}
