import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, index, uniqueIndex } from "drizzle-orm/sqlite-core";

export const stations = sqliteTable("stations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  governorate: text("governorate").notNull(),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
});
export const vehicles = sqliteTable("vehicles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  plateNumber: text("plate_number").notNull().unique(),
  stationId: integer("station_id").references(() => stations.id),
  manufacturer: text("manufacturer"),
  model: text("model"),
  productionYear: integer("production_year"),
  fuelType: text("fuel_type"),
  ambulanceType: text("ambulance_type"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  serviceStatus: text("service_status").notNull().default("active"),
  outOfServiceReason: text("out_of_service_reason"),
  workLocation: text("work_location"),
  fleetSourceRow: integer("fleet_source_row"),
});
export const vehicleMaintenance = sqliteTable("vehicle_maintenance", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vehicleId: integer("vehicle_id").notNull().references(() => vehicles.id),
  stationId: integer("station_id").notNull().references(() => stations.id),
  requestDate: text("request_date").notNull(),
  department: text("department").notNull(),
  odometerKm: real("odometer_km").notNull(),
  requestedRepair: text("requested_repair").notNull(),
  failureCause: text("failure_cause"),
  driverName: text("driver_name").notNull(),
  centerManagerName: text("center_manager_name"),
  circleManagerName: text("circle_manager_name"),
  attachmentKey: text("attachment_key").notNull(),
  attachmentName: text("attachment_name").notNull(),
  attachmentType: text("attachment_type").notNull(),
  status: text("status").notNull().default("open"),
  maintenanceRecommendation: text("maintenance_recommendation"),
  managerRecommendation: text("manager_recommendation"),
  financeRecommendation: text("finance_recommendation"),
  administrativeRecommendation: text("administrative_recommendation"),
  performedWork: text("performed_work"),
  receivedAt: text("received_at"),
  receivedBy: text("received_by"),
  createdBy: text("created_by").notNull(),
  closedBy: text("closed_by"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
}, (table) => [
  index("idx_maintenance_request_date_station_vehicle").on(table.requestDate, table.stationId, table.vehicleId),
  uniqueIndex("idx_maintenance_one_open_vehicle").on(table.vehicleId).where(sql`status = 'open'`),
]);
export const fuelFillings = sqliteTable("fuel_fillings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vehicleId: integer("vehicle_id").notNull().references(() => vehicles.id),
  incidentId: integer("incident_id").references(() => incidents.id),
  filledAt: text("filled_at").notNull(),
  liters: real("liters").notNull(),
  fuelType: text("fuel_type").notNull(),
  odometerKm: real("odometer_km"),
  driverStaffId: integer("driver_staff_id").references(() => staff.id),
  driverName: text("driver_name"),
  filledByStaffId: integer("filled_by_staff_id").references(() => staff.id),
  filledByName: text("filled_by_name").notNull(),
  sourceName: text("source_name"),
  voucherNumber: text("voucher_number"),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const vehicleMovements = sqliteTable("vehicle_movements", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  vehicleId: integer("vehicle_id").notNull().references(() => vehicles.id),
  incidentId: integer("incident_id").references(() => incidents.id),
  driverStaffId: integer("driver_staff_id").references(() => staff.id),
  driverName: text("driver_name"),
  departedAt: text("departed_at").notNull(),
  returnedAt: text("returned_at"),
  kmStart: real("km_start").notNull(),
  kmEnd: real("km_end"),
  destination: text("destination"),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const staff = sqliteTable("staff", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  fullName: text("full_name").notNull(),
  stationId: integer("station_id").references(() => stations.id),
  qualification: text("qualification"),
  cadreType: text("cadre_type").notNull().default("كادر"),
  jobTitle: text("job_title"),
  detail: text("detail"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
});
export const operationalAssignments = sqliteTable("operational_assignments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  workDate: text("work_date").notNull(),
  staffId: integer("staff_id")
    .notNull()
    .references(() => staff.id),
  stationId: integer("station_id")
    .notNull()
    .references(() => stations.id),
  shift: text("shift").notNull(),
  dutyType: text("duty_type").notNull().default("دوام مركز"),
  vehicleId: integer("vehicle_id").references(() => vehicles.id),
  workLocation: text("work_location"),
  attendanceStatus: text("attendance_status").notNull().default("حاضر"),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const coordinations = sqliteTable("coordinations", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  sourceKey: text("source_key").unique(),
  sequenceNumber: integer("sequence_number"),
  coordinationDate: text("coordination_date").notNull(),
  coordinatingAgency: text("coordinating_agency").notNull(),
  vehicleCount: integer("vehicle_count").notNull().default(0),
  coordinationType: text("coordination_type").notNull(),
  resultDescription: text("result_description"),
  ambulancePatients: integer("ambulance_patients").notNull().default(0),
  ambulanceCompanions: integer("ambulance_companions").notNull().default(0),
  busPatients: integer("bus_patients").notNull().default(0),
  coordinationStatus: text("coordination_status").notNull().default("نجح"),
  participatingVehicles: text("participating_vehicles"),
  notesPatients: integer("notes_patients").notNull().default(0),
  notesCompanions: integer("notes_companions").notNull().default(0),
  notesTotal: integer("notes_total").notNull().default(0),
  notes: text("notes"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const incidents = sqliteTable("incidents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  incidentNumber: text("incident_number").notNull().unique(),
  incidentCode: text("incident_code"),
  beneficiaryName: text("beneficiary_name"),
  gender: text("gender").notNull(),
  contact: text("contact"),
  age: integer("age"),
  urgency: text("urgency").notNull(),
  category: text("category").notNull(),
  caseType: text("case_type").notNull(),
  pickupType: text("pickup_type"),
  pickupLocation: text("pickup_location"),
  pickupGovernorate: text("pickup_governorate").notNull(),
  pickupMunicipality: text("pickup_municipality"),
  pickupNeighborhood: text("pickup_neighborhood"),
  dropoffType: text("dropoff_type"),
  dropoffLocation: text("dropoff_location"),
  shift: text("shift").notNull(),
  station: text("station").notNull(),
  vehicle: text("vehicle"),
  vehicleId: integer("vehicle_id").references(() => vehicles.id),
  kmStart: real("km_start"),
  kmEnd: real("km_end"),
  distanceKm: real("distance_km").notNull().default(0),
  callDate: text("call_date").notNull(),
  callTime: text("call_time").notNull(),
  dispatchDate: text("dispatch_date"),
  dispatchTime: text("dispatch_time"),
  onSceneDate: text("on_scene_date"),
  arrivalTime: text("arrival_time"),
  hospitalDate: text("hospital_date"),
  hospitalTime: text("hospital_time"),
  availableDate: text("available_date"),
  clearTime: text("clear_time"),
  responseMinutes: integer("response_minutes").notNull().default(0),
  serviceMinutes: integer("service_minutes").notNull().default(0),
  crew: text("crew"),
  dispatcherPrimary: text("dispatcher_primary"),
  dispatcherSecondary: text("dispatcher_secondary"),
  emtDriver: text("emt_driver"),
  emtLead: text("emt_lead"),
  emtAssist: text("emt_assist"),
  interventions: text("interventions"),
  chiefComplaint: text("chief_complaint"),
  cancelled: integer("cancelled", { mode: "boolean" }).notNull().default(false),
  patientDeceased: integer("patient_deceased", { mode: "boolean" }).notNull().default(false),
  conflictRelated: integer("conflict_related", { mode: "boolean" }).notNull().default(false),
  oxygen: integer("oxygen", { mode: "boolean" }).notNull().default(false),
  bvm: integer("bvm", { mode: "boolean" }).notNull().default(false),
  airway: integer("airway", { mode: "boolean" }).notNull().default(false),
  cpr: integer("cpr", { mode: "boolean" }).notNull().default(false),
  aed: integer("aed", { mode: "boolean" }).notNull().default(false),
  drugs: integer("drugs", { mode: "boolean" }).notNull().default(false),
  woundCare: integer("wound_care", { mode: "boolean" }).notNull().default(false),
  tourniquet: integer("tourniquet", { mode: "boolean" }).notNull().default(false),
  immobilization: integer("immobilization", { mode: "boolean" }).notNull().default(false),
  cervicalCollar: integer("cervical_collar", { mode: "boolean" }).notNull().default(false),
  glucoseCheck: integer("glucose_check", { mode: "boolean" }).notNull().default(false),
  splinting: integer("splinting", { mode: "boolean" }).notNull().default(false),
  delivery: integer("delivery", { mode: "boolean" }).notNull().default(false),
  sourceImportKey: text("source_import_key").unique(),
  sourceIncidentNumber: text("source_incident_number"),
  sourceIncidentCode: text("source_incident_code"),
  importBatch: text("import_batch"),
  dataQualityStatus: text("data_quality_status").notNull().default("ok"),
  dataQualityNotes: text("data_quality_notes"),
  fuelLiters: real("fuel_liters").notNull().default(0),
  notes: text("notes"),
  approvalStatus: text("approval_status").notNull().default("approved"),
  approvedBy: text("approved_by"),
  approvedAt: text("approved_at"),
  rejectionReason: text("rejection_reason"),
  createdBy: text("created_by"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const userProfiles = sqliteTable("user_profiles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  externalUserId: text("external_user_id").notNull().unique(),
  email: text("email"),
  fullName: text("full_name"),
  role: text("role").notNull().default("viewer"),
  station: text("station"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
});
export const auditLogs = sqliteTable("audit_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  actor: text("actor"),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id"),
  details: text("details"),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const notifications = sqliteTable("notifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  recipient: text("recipient"),
  title: text("title").notNull(),
  message: text("message").notNull(),
  type: text("type").notNull().default("info"),
  entityType: text("entity_type"),
  entityId: text("entity_id"),
  isRead: integer("is_read", { mode: "boolean" }).notNull().default(false),
  createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"),
});
export const systemSettings = sqliteTable("system_settings", {
  key: text("key").primaryKey(),
  value: text("value"),
  label: text("label").notNull(),
  category: text("category").notNull().default("general"),
  updatedBy: text("updated_by"),
  updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP"),
});
