import { NextRequest,NextResponse } from "next/server";
import { env } from "@/lib/server-env";
import { getAccess } from "@/lib/access";
import { hashPassword,hasPermission,parsePermissions } from "@/lib/auth";

const denied=()=>NextResponse.json({error:"لا تملكين صلاحية إدارة المستخدمين"},{status:403});
export async function GET(request:NextRequest){const a=await getAccess(request);if(!a.profile)return NextResponse.json({error:"يرجى تسجيل الدخول"},{status:401});const rows=hasPermission(a.profile,"users.manage")?(await env.DB.prepare("SELECT id,username,email,full_name,role,permissions,station,active,last_login_at FROM user_profiles ORDER BY id").all()).results:[];return NextResponse.json({users:rows.map((u:any)=>({...u,permissions:parsePermissions(u.permissions)})),currentUser:{id:a.profile.id,username:a.profile.username,email:a.profile.email,fullName:a.profile.full_name,role:a.profile.role,station:a.profile.station,permissions:parsePermissions(a.profile.permissions)}});}
export async function POST(request:NextRequest){const a=await getAccess(request);if(!hasPermission(a.profile,"users.manage"))return denied();const b=await request.json() as any;const username=String(b.username||"").trim().toLowerCase(),password=String(b.password||"");if(!b.fullName||username.length<3||password.length<8)return NextResponse.json({error:"الاسم واسم المستخدم وكلمة مرور من 8 أحرف مطلوبة"},{status:400});try{const r=await env.DB.prepare("INSERT INTO user_profiles (username,email,full_name,password_hash,role,permissions,station,active) VALUES (?,?,?,?,?,?,?,1)").bind(username,b.email?.trim().toLowerCase()||null,b.fullName.trim(),hashPassword(password),b.role||"custom",JSON.stringify(Array.isArray(b.permissions)?b.permissions:[]),b.station||null).run();return NextResponse.json({ok:true,id:r.meta.last_row_id},{status:201});}catch{return NextResponse.json({error:"اسم المستخدم أو البريد مستخدم مسبقًا"},{status:409});}}
export async function PATCH(request:NextRequest){const a=await getAccess(request);if(!hasPermission(a.profile,"users.manage"))return denied();const b=await request.json() as any;if(!b.id)return NextResponse.json({error:"المستخدم غير محدد"},{status:400});if(Number(b.id)===a.profile?.id&&b.active===false)return NextResponse.json({error:"لا يمكن إيقاف حسابك الحالي"},{status:400});const username=b.username===undefined?null:String(b.username).trim().toLowerCase();const email=b.email===undefined?null:String(b.email).trim().toLowerCase()||null;try{await env.DB.prepare("UPDATE user_profiles SET full_name=COALESCE(?,full_name),username=COALESCE(?,username),email=CASE WHEN ?=1 THEN ? ELSE email END,role=COALESCE(?,role),permissions=COALESCE(?,permissions),station=CASE WHEN ?=1 THEN ? ELSE station END,active=COALESCE(?,active),password_hash=COALESCE(?,password_hash) WHERE id=?").bind(b.fullName?.trim()||null,username,b.email===undefined?0:1,email,b.role||null,Array.isArray(b.permissions)?JSON.stringify(b.permissions):null,b.station===undefined?0:1,b.station||null,b.active===undefined?null:b.active?1:0,b.password?hashPassword(String(b.password)):null,b.id).run();return NextResponse.json({ok:true});}catch{return NextResponse.json({error:"اسم المستخدم أو البريد مستخدم لحساب آخر"},{status:409});}}
